from __future__ import annotations

import argparse
import json
from pathlib import Path

# Marks a file as owned by this script, so reruns know it's safe to regenerate.
# A hand-written report (e.g. copied from report_template.md and filled in)
# never contains this marker, so it is never silently overwritten.
GENERATED_MARKER = "<!-- auto-generated by scripts/generate_report.py: safe to overwrite -->"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--metrics", default="reports/metrics.json")
    parser.add_argument("--out", default="reports/final_report.md")
    args = parser.parse_args()
    metrics = json.loads(Path(args.metrics).read_text())
    lines = [
        GENERATED_MARKER,
        "# Day 10 Reliability Final Report",
        "",
        "## Metrics Summary",
        "",
        "| Metric | Value |",
        "|---|---:|",
    ]
    for key, value in metrics.items():
        if key == "scenarios":
            continue
        lines.append(f"| {key} | {value} |")
    lines += ["", "## Chaos Scenarios", "", "| Scenario | Status |", "|---|---|"]
    for key, value in metrics.get("scenarios", {}).items():
        lines.append(f"| {key} | {value} |")
    lines += [
        "",
        "## Analysis TODO(student)",
        "",
        "Explain what failed, why the fallback path worked or did not work, and what you would change before production.",
    ]

    out_path = Path(args.out)
    if out_path.exists() and GENERATED_MARKER not in out_path.read_text(encoding="utf-8"):
        redirected = out_path.with_name(out_path.stem + ".autogen" + out_path.suffix)
        print(
            f"{out_path} already contains a hand-written report — "
            f"writing the auto-generated metrics summary to {redirected} instead "
            f"so it is not overwritten."
        )
        out_path = redirected

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines))
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
